image: docker:latest

test:
  stage: test
  image: node:13
  script:
    - npm install
    - npm test
  cache:
    key: node-modules
    untracked: true
    paths:
      - node_modules/

deploy:
  stage: deploy
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - ./build-images.sh $CI_COMMIT_REF_NAME
  only:
    - tags

