image: docker:latest

test:
  stage: test
  image: node:13
  script:
    - npm install
    - npm test
  cache:
    key: node-modules
    untracked: true
    paths:
      - node_modules/
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: always

deploy:
  stage: deploy
  image: docker:latest
  before_script:
    - apk add --no-cache bash
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - ./build-images.sh $CI_COMMIT_REF_NAME
  rules:
    - if: $CI_COMMIT_TAG
      when: always
    - when: never

