image: docker:latest

services:
  - docker:dind

test:
  stage: test
  image: node:8
  script:
    - npm install
    - npm test
  cache:
    untracked: true
    paths:
      - node_modules/

deploy:
  stage: deploy
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  only:
    - tags

